/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppVolumesRouteImport } from './routes/_app.volumes'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppKeysRouteImport } from './routes/_app.keys'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppVolumesIndexRouteImport } from './routes/_app.volumes.index'
import { Route as ApiNsSocketRouteImport } from './routes/api/ns/socket'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppVolumesVolumeIdRouteImport } from './routes/_app.volumes.$volumeId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVolumesRoute = AppVolumesRouteImport.update({
  id: '/volumes',
  path: '/volumes',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppKeysRoute = AppKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppVolumesIndexRoute = AppVolumesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVolumesRoute,
} as any)
const ApiNsSocketRoute = ApiNsSocketRouteImport.update({
  id: '/api/ns/socket',
  path: '/api/ns/socket',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVolumesVolumeIdRoute = AppVolumesVolumeIdRouteImport.update({
  id: '/$volumeId',
  path: '/$volumeId',
  getParentRoute: () => AppVolumesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/billing': typeof AppBillingRoute
  '/keys': typeof AppKeysRoute
  '/team': typeof AppTeamRoute
  '/volumes': typeof AppVolumesRouteWithChildren
  '/volumes/$volumeId': typeof AppVolumesVolumeIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ns/socket': typeof ApiNsSocketRoute
  '/volumes/': typeof AppVolumesIndexRoute
}
export interface FileRoutesByTo {
  '/accept-invitation': typeof AcceptInvitationRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/billing': typeof AppBillingRoute
  '/keys': typeof AppKeysRoute
  '/team': typeof AppTeamRoute
  '/': typeof AppIndexRoute
  '/volumes/$volumeId': typeof AppVolumesVolumeIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ns/socket': typeof ApiNsSocketRoute
  '/volumes': typeof AppVolumesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/keys': typeof AppKeysRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/volumes': typeof AppVolumesRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/volumes/$volumeId': typeof AppVolumesVolumeIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ns/socket': typeof ApiNsSocketRoute
  '/_app/volumes/': typeof AppVolumesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/billing'
    | '/keys'
    | '/team'
    | '/volumes'
    | '/volumes/$volumeId'
    | '/api/auth/$'
    | '/api/ns/socket'
    | '/volumes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invitation'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/billing'
    | '/keys'
    | '/team'
    | '/'
    | '/volumes/$volumeId'
    | '/api/auth/$'
    | '/api/ns/socket'
    | '/volumes'
  id:
    | '__root__'
    | '/_app'
    | '/accept-invitation'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/_app/billing'
    | '/_app/keys'
    | '/_app/team'
    | '/_app/volumes'
    | '/_app/'
    | '/_app/volumes/$volumeId'
    | '/api/auth/$'
    | '/api/ns/socket'
    | '/_app/volumes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  PrivacyRoute: typeof PrivacyRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TermsRoute: typeof TermsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiNsSocketRoute: typeof ApiNsSocketRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/volumes': {
      id: '/_app/volumes'
      path: '/volumes'
      fullPath: '/volumes'
      preLoaderRoute: typeof AppVolumesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/keys': {
      id: '/_app/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AppKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/volumes/': {
      id: '/_app/volumes/'
      path: '/'
      fullPath: '/volumes/'
      preLoaderRoute: typeof AppVolumesIndexRouteImport
      parentRoute: typeof AppVolumesRoute
    }
    '/api/ns/socket': {
      id: '/api/ns/socket'
      path: '/api/ns/socket'
      fullPath: '/api/ns/socket'
      preLoaderRoute: typeof ApiNsSocketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/volumes/$volumeId': {
      id: '/_app/volumes/$volumeId'
      path: '/$volumeId'
      fullPath: '/volumes/$volumeId'
      preLoaderRoute: typeof AppVolumesVolumeIdRouteImport
      parentRoute: typeof AppVolumesRoute
    }
  }
}

interface AppVolumesRouteChildren {
  AppVolumesVolumeIdRoute: typeof AppVolumesVolumeIdRoute
  AppVolumesIndexRoute: typeof AppVolumesIndexRoute
}

const AppVolumesRouteChildren: AppVolumesRouteChildren = {
  AppVolumesVolumeIdRoute: AppVolumesVolumeIdRoute,
  AppVolumesIndexRoute: AppVolumesIndexRoute,
}

const AppVolumesRouteWithChildren = AppVolumesRoute._addFileChildren(
  AppVolumesRouteChildren,
)

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppKeysRoute: typeof AppKeysRoute
  AppTeamRoute: typeof AppTeamRoute
  AppVolumesRoute: typeof AppVolumesRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppKeysRoute: AppKeysRoute,
  AppTeamRoute: AppTeamRoute,
  AppVolumesRoute: AppVolumesRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  PrivacyRoute: PrivacyRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TermsRoute: TermsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiNsSocketRoute: ApiNsSocketRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
